services:
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME:-financiera-web}
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
